
import type { Metadata } from 'next'
import './globals.css'
// import { AppProviders } from '@/components/app-providers'
// import { AppLayout } from '@/components/app-layout'
import React from 'react'
import { SolanaProvider } from '@/components/solana/solana-provider'

export const metadata: Metadata = {
  title: 'OracleMind',
  description: 'Generated by create-solana-dapp',
}

const links: { label: string; path: string }[] = [
  // More links...
  { label: 'Home', path: '/' },
  { label: 'Account', path: '/account' },
  { label: 'Counter Program', path: '/counter' },
]



export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  // const ref = React.useRef(null);
  // const { scrollYProgress } = useScroll({
  //   target: ref,
  //   offset: ["start start", "end start"],
  // });
  // const pathLengthFirst = useTransform(scrollYProgress, [0, 0.8], [0.2, 1.2]);
  // const pathLengthSecond = useTransform(scrollYProgress, [0, 0.8], [0.15, 1.2]);
  // const pathLengthThird = useTransform(scrollYProgress, [0, 0.8], [0.1, 1.2]);
  // const pathLengthFourth = useTransform(scrollYProgress, [0, 0.8], [0.05, 1.2]);
  // const pathLengthFifth = useTransform(scrollYProgress, [0, 0.8], [0, 1.2]);
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`antialiased`}>
        <SolanaProvider>
          {children}
        </SolanaProvider>
      </body>
    </html>
  )
}

// Patch BigInt so we can log it using JSON.stringify without any errors
declare global {
  interface BigInt {
    toJSON(): string
  }
}

BigInt.prototype.toJSON = function () {
  return this.toString()
}
